defaultAPI: https://express-api-shadowfork-three.elrond.ro
defaultPROXY: https://proxy-shadowfork-three.elrond.ro
deployedGuildAddress: erd1qqqqqqqqqqqqqpgq0sqcgdlgt5mrp3l4qhw6mzpu3z45778qkg2sx8xm2q
divisionSafetyConstant: 10000000000000000000
farmingToken: TESTUTK-477d07
guildConfigBYTEPATH: /home/multiversx/Documents/guilds_py/wasm/guild-sc-config.wasm
guildConfigScAddressModel: erd1qqqqqqqqqqqqqpgqy7e6yjv5rxcath8g8tr2dzrzs3qwhxmckg2sst5228
guildFactoryBYTEPATH: /home/multiversx/Documents/guilds_py/wasm/guild-factory.wasm
guildFactoryScAddress: erd1qqqqqqqqqqqqqpgqejh52ngpgd0e4jja0emzv0hunrs2s4shkg2sh92970
guildSCBYTEPATH: /home/multiversx/Documents/guilds_py/wasm/guild-sc.wasm
guildScAddressModel: erd1qqqqqqqqqqqqqpgq8m4pudapr5r09xlesdn3482gcztztz3pkg2swrcs62
perBlockRewardAmount: 40000000000000000
signingWalletAddress: erd1a2x0azarwsag9svwdn23pjramat7zcjceqd44yh4g7jx4pugkg2s3jwlel
signingWalletPemPath: ./../defi-wallet.pem
