deployedGuildAddress: ""
# Farming token ticker
farmingToken: UTKT1-ab75ee

# Models for guild and guild config needed in factory and guild deployments
guildConfigScAddressModel: erd1qqqqqqqqqqqqqpgqxvuhv3hk7wx6vt2wm56jm70vknyvwx74zeus7l7puc
guildScAddressModel: erd1qqqqqqqqqqqqqpgqmm5deah5j7lnjmt620gqe95pj3cnangezeus8u6l69

# Factory contract address
guildFactoryScAddress: ""

# Wallet address and pem path for signing transactions
signingWalletAddress: erd1h4wvr5dz3mxeflq0kkf3e0qhz457np98jxpwfzwstr2sz8zfzeusaq0nh5
signingWalletPemPath: ./defi-wallet.pem

# Deployment params
divisionSafetyConstant: 1000000000000
perBlockRewardAmount: 10000000
